kind: Deployment
apiVersion: apps/v1
metadata:
  name: parking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parking
  template:
    metadata:
      labels:
        app: parking
    spec:
      containers:
        - name: parking
          image: parking
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: parking
spec:
  type: LoadBalancer
  ports:
    - name: parking
      port: 32772
      targetPort: 80
  selector:
    app: parking
